### ISSUE TITLE
Use theme values from SilverBullet space

### ISSUE THREAD

**Issue by joekrill** [joekrill/silverbullet-treeview#1]
Currently the theme values are hard-coded. Ideally the theme values would be injected from SilverBullet so any customizations are applied. Pretty sure this is going to require changes in SilverBullet codebase.

**Comment by MadMaxMcKinney** [comment]
@joekrill Any reason you closed this issue? I stumbled upon this today when trying to make some color tweaks.

**Comment by joekrill** [comment]
> [@joekrill](https://github.com/joekrill) Any reason you closed this issue? I stumbled upon this today when trying to make some color tweaks.

@MadMaxMcKinney It was fixed with [this commit](https://github.com/joekrill/silverbullet-treeview/commit/2896ff5b5ab4afeaee8d8aca5a141d32e2bdb911) at the time. But something may have changed that's caused the problem to surface again.
