### ISSUE TITLE
Add option to use a custom base directory instead of the root of the space

### ISSUE THREAD

**Issue by simone-viozzi** [joekrill/silverbullet-treeview#10]
To avoid confusion with the default silverbullet folders, i have everything in `/notes`.

I would like to set this folder as root for the TreeView.

**Comment by joekrill** [comment]
This can sort of be handled with the `pageExcludeRegex` feature that was added. You could do something liike:

```
treeview:
  pageExcludeRegex: "^(?!notes)"
```

It will still show the "notes" folder itself, though so not sure if this gets you exactly what you want?

**Comment by joekrill** [comment]
Quick update: I made some modifications to the treeview filtering settings. The exclusion rule to only show the notes folder would now be handled like this:

```yaml
treeview:
  exclusions:
  - type: "regex"
    rule: "^notes"
    negate: true
```

Let me know if you think I should still consider creating a root folder setting of some sort. If not feel free to close this issue. But if so, what would be the difference? Would the "notes" folder (in your case) simple not exist and everything inside of it would be flattened and appear as root nodes in the tree?

**Comment by simone-viozzi** [comment]
thank you!
