### ISSUE TITLE
Add mechanism to not show all pages or highlight some differently

### ISSUE THREAD

**Issue by raisinbear** [joekrill/silverbullet-treeview#12]
Hi,
forst off thanks for the great work! I really appreciate having an overview over all pages. I just thought it might be ever so slightly less distracting if it were possible to hide some of the notes from the treeview or maybe show them in different color or at the top or bottom of the list. Background is that when scanning the tree, system pages like  `SETTINGS`, `PLUGS`, `index` and the `Library` folder of course show up as well, but I'm rarely looking for these.
Anyways, thanks for reading 😉

**Comment by djm2k** [comment]
I've implemented a new config option `pageExcludeRegex` in this PR: https://github.com/joekrill/silverbullet-treeview/pull/16

```yaml
  # Regular Expression string to exclude pages from the tree
  # - Any page that is all-caps: [A-Z]+
  # - A specific set of pages: (?:SETTINGS|PLUGS|index|Library)
  pageExcludeRegex: (?:SETTINGS|PLUGS|index|Library)
```

Does that work for you? You can test it out using my fork before the PR is merged:
```yaml
#- github:joekrill/silverbullet-treeview/treeview.plug.js
- github:djm2k/silverbullet-treeview/treeview.plug.js
```

**Comment by raisinbear** [comment]
> I've implemented a new config option `pageExcludeRegex` in this PR: #16
> 
> ```yaml
>   # Regular Expression string to exclude pages from the tree
>   # - Any page that is all-caps: "^[A-Z]+$"
>   # - A specific set of pages: "^(?:SETTINGS|PLUGS|index|Library)$"
>   # - Any path containing Hidden: "Hidden" e.g. test/Hidden/page1
>   pageExcludeRegex: "^(?:SETTINGS|PLUGS|index|Library)$"
> ```
> 
> Does that work for you? You can test it out using my fork before the PR is merged:
> 
> ```yaml
> #- github:joekrill/silverbullet-treeview/treeview.plug.js
> - github:djm2k/silverbullet-treeview/treeview.plug.js
> ```

Awesome, thanks so much! Working like a charm. 🤩

Just a short note for regex noobs like me, should that make it to the readme: had to add ` \/.*` in the example after `Library` to make it match against the `Library` folder.
