### ISSUE TITLE
Treeview Not Working in SilverBullet 0.8.4

### ISSUE THREAD

**Issue by iamdangry** [joekrill/silverbullet-treeview#21]
Treeview doesn't work in SilverBullet 0.8.4.

Error output to console after toggling Treeview:
![image](https://github.com/user-attachments/assets/0246432d-0aa7-4934-a440-4a6bdaa40584)

Rolling back to 0.8.2 fixes it.

**Comment by joekrill** [comment]
Would you mind checking to see if you get the same issue when you try to open the Markdown Preview (i.e. running the `Markdown Preview: Toggle` command or using `Cmd-Chift-P`)? I think this is an issue with opening any panel.

**Comment by joekrill** [comment]
I just [created a PR](https://github.com/silverbulletmd/silverbullet/pull/989) that fixes this issue, but unfortunately it won't be fixed until the next SilverBullet release. So in the meantime the only fix is to either stay at v0.8.2 for now, or don't use the tree view (or the Markdown Preview, for that matter, which is also affected by this).

**Comment by iamdangry** [comment]
Back in business with 0.8.5. Thanks Joe!
