### ISSUE TITLE
`reveal-current-page` may be unnecessary 

### ISSUE THREAD

**Issue by slashtechno** [joekrill/silverbullet-treeview#8]
It seems the button with the action `reveal-current-page` may be unnecessary. If I understand correctly, its function is to highlight the current page. However, it seems the default page is always highlighted anyway. In addition, pressing a page in the treeview navigates to it.
![The button to reveal the current page](https://github.com/joekrill/silverbullet-treeview/assets/77907286/75faa5ca-d751-4276-bb18-09cd4dd59cf2)

**Comment by slashtechno** [comment]
Just realized its use when the folder/directory containing the current page is collapsed.

**Comment by joekrill** [comment]
> Just realized its use when the folder/directory containing the current page is collapsed.

Yup that's exactly why I added it: It's useful if you're on a deeply nested page and you "Collapse All". Also if you have a lot of flat pages and you scroll the tree to a point where the current page is not visible - this will scroll you back to the current page.

Could be worth adding the ability for these buttons to be removed via settings, though.
